"""Consumed contracts of the private JavaScript module, not a Python engine."""

from array import array
from collections.abc import Sequence
from typing import Protocol

from pyodide.ffi import JsProxy

class RuntimeTensor(Protocol):
    @property
    def shape(self) -> Sequence[int]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def requiresGrad(self) -> bool: ...
    def add(self, right: RuntimeTensor) -> RuntimeTensor: ...
    def mul(self, right: RuntimeTensor) -> RuntimeTensor: ...
    def sum(self) -> RuntimeTensor: ...
    def view(self, shape: JsProxy) -> RuntimeTensor: ...
    def close(self) -> None: ...

class RuntimeFailure(Protocol):
    code: str

class RuntimeException(Protocol):
    # Pyodide 314.0.6 exposes this on JsException at runtime, but omits it
    # from its distributed declaration. Real interpreter tests cover it.
    js_error: RuntimeFailure

class ObservedArray(Protocol):
    def to_py(self) -> memoryview: ...

def observe(handle: RuntimeTensor) -> ObservedArray: ...
def tensorFromBuffer(
    buffer: array[float], shape: JsProxy, requiresGrad: bool = False
) -> RuntimeTensor: ...
def grad(
    output: RuntimeTensor, inputs: JsProxy, gradient: RuntimeTensor | None
) -> Sequence[RuntimeTensor]: ...

session: object
