"""Consumed contracts of the private JavaScript module, not a Python engine."""

from array import array
from collections.abc import Sequence
from typing import Protocol

from pyodide.ffi import JsNull, JsProxy

class RuntimeTensor(Protocol):
    @property
    def shape(self) -> Sequence[int]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def requiresGrad(self) -> bool: ...
    @property
    def grad(self) -> RuntimeTensor | JsNull | None: ...
    @grad.setter
    def grad(self, value: RuntimeTensor | JsNull | None) -> None: ...
    def add(self, right: RuntimeTensor) -> RuntimeTensor: ...
    def mul(self, right: RuntimeTensor) -> RuntimeTensor: ...
    def copy_(self, source: RuntimeTensor) -> RuntimeTensor: ...
    def sum(self) -> RuntimeTensor: ...
    def view(self, shape: JsProxy) -> RuntimeTensor: ...
    def close(self) -> None: ...

class RuntimeFailure(Protocol):
    code: str

class RuntimeException(Protocol):
    # Pyodide 314.0.6 exposes this on JsException at runtime, but omits it
    # from its distributed declaration. Real interpreter tests cover it.
    js_error: RuntimeFailure

class ObservedArray(Protocol):
    def to_py(self) -> memoryview: ...

def observe(handle: RuntimeTensor) -> ObservedArray: ...
def getRecordingMode() -> bool: ...
def enterNoGrad() -> bool: ...
def exitNoGrad(previous: bool) -> None: ...
def tensorFromBuffer(
    buffer: array[float],
    shape: JsProxy,
    requiresGrad: bool = False,
    device: str = "cpu",
) -> RuntimeTensor: ...
def grad(
    output: RuntimeTensor, inputs: JsProxy, gradient: RuntimeTensor | None
) -> Sequence[RuntimeTensor]: ...
def backward(
    output: RuntimeTensor, inputs: JsProxy | None, gradient: RuntimeTensor | None
) -> None: ...
def exposureKey(handle: RuntimeTensor) -> int: ...
def shouldWarnGradient(handle: RuntimeTensor) -> bool: ...
def releaseExposure(handle: RuntimeTensor) -> None: ...

class OptimizerLease(Protocol):
    def assertOpen(self) -> None: ...
    def beginStep(self) -> bool: ...
    def setRecording(self, recording: bool) -> None: ...
    def hasGradients(self, index: int) -> bool: ...
    def stepGroup(self, index: int, alphaBits: int) -> None: ...
    def zeroGrad(self, setToNone: bool) -> None: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...

def registerSGD(groups: JsProxy) -> OptimizerLease: ...
def isOptimizableParameter(handle: RuntimeTensor) -> bool: ...

session: object
